### ISSUE TITLE
No se deben subir archivos innecesarios al repositorio

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas#1]
No deben subir al repositorio archivos innecesarios como:
* .idea 
* .DS_Store

Al subir este tipo de archivos se puede llegar a generar conflictos innecesarios, por ejemplo, si los otros usuarios emplean una configuración de WebStorm diferente.

**Comment by edme88** [comment]
Este error continua ocurriendo
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/assets/8345007/9d8bb7ea-25e5-4848-9e32-edfe328e09c0)

**Comment by IvanArrieta** [comment]
Corregido

**Comment by edme88** [comment]
El archivo .idea fue subido nuevamente
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/assets/8345007/2aa3c222-0b34-4925-bcd6-93045377cb6d)
