### ISSUE TITLE
Toda tabla debe contener <caption>

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas#12]
https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/blob/6eb8b7606ea4d89b5144fafe84e9c26699e48cc3/GuitarChords/Acordes.html#L32

https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/blob/6eb8b7606ea4d89b5144fafe84e9c26699e48cc3/GuitarChords/Acordes.html#L79

https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/blob/6eb8b7606ea4d89b5144fafe84e9c26699e48cc3/GuitarChords/Acordes.html#L126

https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/blob/6eb8b7606ea4d89b5144fafe84e9c26699e48cc3/GuitarChords/Acordes.html#L173

https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/blob/6eb8b7606ea4d89b5144fafe84e9c26699e48cc3/GuitarChords/Acordes.html#L220

https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/blob/6eb8b7606ea4d89b5144fafe84e9c26699e48cc3/GuitarChords/Acordes.html#L269

https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/blob/6eb8b7606ea4d89b5144fafe84e9c26699e48cc3/GuitarChords/Acordes.html#L316

https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/blob/6eb8b7606ea4d89b5144fafe84e9c26699e48cc3/GuitarChords/Acordes.html#L410

https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/blob/6eb8b7606ea4d89b5144fafe84e9c26699e48cc3/GuitarChords/Acordes.html#L457

**Comment by edme88** [comment]
Como les comenté en https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/issues/13 , Todas las correcciones solicitadas para el primer parcial deben implementarse (Así sean de GuitarChords ó WhereToWatch)

**Comment by IvanArrieta** [comment]
Corregido
