### ISSUE TITLE
Debe haber navegación entre todas las páginas

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas#16]
Al ingresar a la página de una película random sugerida o de una película específica no hay forma de volver a la página anterior (que no sea presionando el botón back del navegador).
Recuerden que es importante la navegación entre todas las páginas.
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/assets/8345007/384fd8e7-bbbb-4772-872d-64f9a54d8e2d)

**Comment by IvanArrieta** [comment]
Solucionado con boton de volver
