### ISSUE TITLE
Comportamiento incorrecto en la página luego de buscar y volver

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas#17]
Pasos para reproducir el error)
1) Ingresar a https://ucc-labcompu2.github.io/proyecto2023-arrieta-delapena-douglas/WhereToWatch/
2) En el campo de búsqueda escribir "Casablanca" y presionar el botón de lupa
3) Presionar cualquier película
4) Volver a la página principal

Resultado Actual: La palabra buscada "Casablanca" continua escrita en el input, pero los resultados en la parte inferior no coinciden.

Resultado Esperado: O bien, el input debe borrarse al volver a la página, o bien, los resultados de la búsqueda deben preservarse. Pero es importante que la página posea un comportamiento consistente.

![imagen](https://github.com/UCC-LabCompu2/proyecto2023-arrieta-delapena-douglas/assets/8345007/1947bee3-5bed-4892-8eba-a7c7d1e7482a)

**Comment by IvanArrieta** [comment]
Parte se soluciono agregando el boton para volver al inicio y para asegurarse que este bien agregue la funcion clearSearchBar()
